// js/vocabulary.js

const vocabulary = {
    unit0: [
        { french: "Bienvenue!", german: "Willkommen!" },
        { french: "Bonjour!", german: "Guten Tag!; Grüß Gott!" },
        { french: "Salut! (fam.)", german: "Hallo!; Grüß dich!; Servus!" },
        { french: "Ça va?", german: "Wie geht’s?" },
        { french: "oui", german: "ja" },
        { french: "merci", german: "danke" },
        { french: "Salut! (fam.)", german: "Tschüs!; Servus!" },
        { french: "A plus! (fam.)", german: "Bis später!" },
        { french: "bien (adv.)", german: "gut (Adv.)" },
        { french: "Au revoir!", german: "Auf Wiedersehen!" },
        { french: "Moustique", german: "Name eines Hundes" },
        { french: "un ami/une amie", german: "ein Freund/eine Freundin" },
        { french: "Bonjour, les amis!", german: "Guten Tag, Freunde!" },
        { french: "je m’appelle", german: "ich heiße" },
        { french: "et", german: "und" },
        { french: "toi", german: "du (betont)" },
        { french: "moi", german: "ich (betont)" }
    ],
    unit1: [
        { french: "Paris", german: "Paris (Hauptstadt Frankreichs)" },
        { french: "Malabar", german: "Name eines Hundes" },
        { french: "Viens!", german: "Komm! (Aufforderung)" },
        { french: "papa", german: "Papa" },
        { french: "vite (adv.)", german: "schnell (Adv.)" },
        { french: "Miaou!", german: "Miau!" },
        { french: "Ouah, ouah!", german: "Wau, wau!" },
        { french: "S.P.A. (la Société Protectrice des Animaux)", german: "die S.P.A. (französische Tierschutzgesellschaft)" },
        { french: "Qui est-ce?", german: "Wer ist das?" },
        { french: "Attention!", german: "Achtung!; Vorsicht!" },
        { french: "non", german: "nein" },
        { french: "Pardon.", german: "Entschuldigung." },
        { french: "Comment?", german: "Wie? (Fragewort)" },
        { french: "Tu t’appelles comment?", german: "Wie heißt du?" },
        { french: "c’est", german: "das ist" },
        { french: "je suis", german: "ich bin" },
        { french: "voilà", german: "da ist; da sind" },
        { french: "ici", german: "hier; hierher" },
        { french: "un chat", german: "eine Katze" },
        { french: "un chien", german: "ein Hund" },
        { french: "mais", german: "aber" },
        { french: "tu es", german: "du bist" },
        { french: "de/d’", german: "aus; von" },
        { french: "aussi", german: "auch" },
        { french: "super (inv.)", german: "super; toll" },
        { french: "un garçon", german: "ein Junge; ein Bub" },
        { french: "une fille", german: "ein Mädchen; eine Tochter" },
        { french: "il est", german: "er ist" },
        { french: "elle est", german: "sie ist" },
        { french: "un animal", german: "ein Tier" },
        { french: "Ça ne va pas.", german: "Das geht nicht." },
        { french: "une chanson", german: "ein Lied" },
        { french: "fantastique", german: "fantastisch; toll" },
        { french: "bizarre", german: "komisch; merkwürdig" },
        { french: "un copain/une copine (fam.)", german: "ein Freund/eine Freundin" },
        { french: "une dame", german: "eine Dame; eine Frau" },
        { french: "un monsieur", german: "ein Herr; ein Mann" },
        { french: "Toulouse", german: "Toulouse" },
        { french: "Strasbourg", german: "Straßburg" },
        { french: "Brest", german: "Brest" },
        { french: "Nice", german: "Nizza" },
        { french: "madame …", german: "Frau …" },
        { french: "mademoiselle ...", german: "Fräulein …" },
        { french: "Bof! (fam.)", german: "Na ja; Ach. (ugs.)" },
        { french: "un", german: "eins" },
        { french: "zéro", german: "null" },
        { french: "deux", german: "zwei" },
        { french: "trois", german: "drei" },
        { french: "quatre", german: "vier" },
        { french: "cinq", german: "fünf" },
        { french: "six", german: "sechs" },
        { french: "sept", german: "sieben" },
        { french: "huit", german: "acht" },
        { french: "neuf", german: "neun" },
        { french: "dix", german: "zehn" },
        { french: "onze", german: "elf" },
        { french: "douze", german: "zwölf" },
        { french: "un style", german: "ein Stil" },
        { french: "le reggae", german: "der Reggae" },
        { french: "l’électro", german: "Electro" },
        { french: "une mélodie", german: "eine Melodie" },
        { french: "un rythme", german: "ein Rhythmus" },
        { french: "une voix", german: "eine Stimme" }
    ],
    unit2: [
        { french: "un magasin", german: "ein Geschäft" },
        { french: "un journal/des journaux", german: "eine Zeitung/Zeitungen" },
        { french: "une BD", german: "ein Comic" },
        { french: "une affiche", german: "ein Plakat" },
        { french: "Qu’est-ce que c’est?", german: "Was ist das?" },
        { french: "à (Paris)", german: "in (Paris)" },
        { french: "une maison", german: "ein Haus" },
        { french: "une maison de la presse", german: "ein Zeitschriftenladen" },
        { french: "que", german: "was" },
        { french: "Que fait Léo?", german: "Was macht Leo?" },
        { french: "regarder qc", german: "etw. anschauen" },
        { french: "parler", german: "sprechen" },
        { french: "avec", german: "mit" },
        { french: "chercher qn/qc", german: "jdn./etw. suchen" },
        { french: "arriver", german: "ankommen" },
        { french: "en français", german: "auf Französisch" },
        { french: "un stylo", german: "ein Stift" },
        { french: "une gomme", german: "ein Radiergummi" },
        { french: "un livre", german: "ein Buch" },
        { french: "un cahier", german: "ein Heft" },
        { french: "un crayon", german: "ein Bleistift" },
        { french: "un truc (fam.)", german: "ein Ding (ugs.)" },
        { french: "une trousse", german: "ein Mäppchen" },
        { french: "une feuille", german: "ein Blatt" },
        { french: "un cartable", german: "eine Schultasche" },
        { french: "un classeur", german: "ein Ordner" },
        { french: "un sac à dos", german: "ein Rucksack" },
        { french: "français/française", german: "französisch/Franzose/Französin" },
        { french: "écouter qn/qc", german: "jdm./etw. zuhören" },
        { french: "trouver qn/qc", german: "jdn./etw. finden" },
        { french: "travailler", german: "arbeiten" },
        { french: "porter qc", german: "etw. tragen" },
        { french: "dans", german: "in" },
        { french: "une rue", german: "eine Straße" },
        { french: "dans la rue", german: "auf der Straße" },
        { french: "entrer", german: "eintreten" },
        { french: "euh …", german: "äh …" },
        { french: "là", german: "da" },
        { french: "Chut!", german: "Pst!" },
        { french: "pour", german: "für" },
        { french: "une école", german: "eine Schule" },
        { french: "en vacances (f. pl.)", german: "in den Ferien" },
        { french: "Tiens!", german: "Sieh mal! / Schau!" },
        { french: "une grand-mère", german: "eine Großmutter" },
        { french: "un carton", german: "ein Karton" },
        { french: "un ami/une amie", german: "ein Freund/eine Freundin" },
        { french: "Zut! (fam.)", german: "Mist! (ugs.)" },
        { french: "une catastrophe", german: "eine Katastrophe" },
        { french: "il dit/elle dit", german: "er sagt/sie sagt" },
        { french: "être", german: "sein" },
        { french: "devant", german: "vor" },
        { french: "habiter", german: "wohnen" },
        { french: "la rue Nollet", german: "die Nolletstraße" },
        { french: "où", german: "wo" },
        { french: "la rue Truffaut", german: "die Truffautstraße" },
        { french: "un t-shirt", german: "ein T-Shirt" },
        { french: "le rugby", german: "Rugby" },
        { french: "le judo", german: "Judo" },
        { french: "Qu’est-ce que …?", german: "Was ...?" },
        { french: "le sport", german: "Sport" },
        { french: "la musique", german: "Musik" },
        { french: "un frère", german: "ein Bruder" },
        { french: "une sœur", german: "eine Schwester" },
        { french: "sympa", german: "nett / sympathisch" },
        { french: "détester qn/qc", german: "jdn./etw. hassen" },
        { french: "ça", german: "das" },
        { french: "d’accord", german: "einverstanden" },
        { french: "alors", german: "also / dann" },
        { french: "Ouf!", german: "Uff! / Puh!" },
        { french: "aimer qn/qc", german: "jdn./etw. mögen / lieben" },
        { french: "le rock", german: "Rockmusik" },
        { french: "le foot(ball)", german: "Fußball" },
        { french: "un vélo", german: "ein Fahrrad" },
        { french: "la techno", german: "Techno" },
        { french: "le rap", german: "Rap" },
        { french: "la gymnastique", german: "Gymnastik" },
        { french: "une chanson", german: "ein Lied" },
        { french: "un saxophone", german: "ein Saxophon" },
        { french: "un piano", german: "ein Klavier" },
        { french: "un dessin", german: "eine Zeichnung" },
        { french: "le basket(ball)", german: "Basketball" },
        { french: "l’athlétisme (m.)", german: "Leichtathletik" },
        { french: "le roller", german: "Inlineskaten" },
        { french: "un cinéma", german: "ein Kino" },
        { french: "le VTT", german: "Mountainbike" },
        { french: "la lecture", german: "das Lesen" }
    ],
    unit3: [
        { french: "un anniversaire", german: "ein Geburtstag" },
        { french: "une idée", german: "eine Idee" },
        { french: "des", german: "(Pluralartikel, keine direkte Übersetzung)" },
        { french: "un cadeau", german: "ein Geschenk" },
        { french: "la FNAC", german: "die FNAC (frz. Ladenkette)" },
        { french: "bientôt", german: "bald" },
        { french: "Ah, bon?", german: "Ach so? / Wirklich?" },
        { french: "une histoire", german: "eine Geschichte" },
        { french: "ou", german: "oder" },
        { french: "un ordinateur", german: "ein Computer" },
        { french: "un CD/des CD", german: "eine CD/CDs" },
        { french: "il y a", german: "es gibt" },
        { french: "ensemble", german: "zusammen" },
        { french: "d’abord", german: "zuerst" },
        { french: "Qu’est-ce qu’il y a?", german: "Was gibt es? / Was ist los?" },
        { french: "Bien sûr!", german: "Natürlich! / Klar!" },
        { french: "préparer qc", german: "etw. vorbereiten" },
        { french: "la France", german: "Frankreich" },
        { french: "l’Allemagne (f.)", german: "Deutschland" },
        { french: "en Allemagne", german: "in Deutschland" },
        { french: "Allô?", german: "Hallo? (am Telefon)" },
        { french: "un train", german: "ein Zug" },
        { french: "Cologne", german: "Köln" },
        { french: "demain", german: "morgen" },
        { french: "ton/ta/tes", german: "dein/deine/deine (Plural)" },
        { french: "mon/ma/mes", german: "mein/meine/meine (Plural)" },
        { french: "C’est dommage.", german: "Das ist schade." },
        { french: "inviter qn", german: "jdn. einladen" },
        { french: "allemand", german: "deutsch / Deutscher" },
        { french: "en allemand", german: "auf Deutsch" },
        { french: "à bientôt", german: "bis bald" },
        { french: "maman (f.)", german: "Mama" },
        { french: "une chambre", german: "ein Zimmer" },
        { french: "une bougie", german: "eine Kerze" },
        { french: "un gâteau/des gâteaux", german: "ein Kuchen/Kuchen" },
        { french: "ranger qc", german: "etw. aufräumen" },
        { french: "s’il te plaît", german: "bitte (du)" },
        { french: "s’il vous plaît", german: "bitte (Sie)" },
        { french: "maintenant", german: "jetzt" },
        { french: "une affaire", german: "eine Sache" },
        { french: "toujours", german: "immer" },
        { french: "aujourd’hui", german: "heute" },
        { french: "une famille", german: "eine Familie" },
        { french: "un enfant", german: "ein Kind" },
        { french: "les grands-parents (m.)", german: "die Großeltern" },
        { french: "un grand-père", german: "ein Großvater" },
        { french: "les parents (m.)", german: "die Eltern" },
        { french: "un père", german: "ein Vater" },
        { french: "une mère", german: "eine Mutter" },
        { french: "un oncle", german: "ein Onkel" },
        { french: "une tante", german: "eine Tante" },
        { french: "un fils", german: "ein Sohn" },
        { french: "une demi-sœur", german: "eine Halbschwester" },
        { french: "un demi-frère", german: "ein Halbbruder" },
        { french: "un cousin/une cousine", german: "ein Cousin/eine Cousine" },
        { french: "décembre (m.)", german: "Dezember" },
        { french: "son/sa/ses (+ Nomen)", german: "sein/ihr/seine (Plural)" },
        { french: "C’est ça?", german: "Ist das so? / Stimmt das?" },
        { french: "encore", german: "noch / wieder" },
        { french: "un DVD", german: "eine DVD" },
        { french: "un jeu/des jeux", german: "ein Spiel/Spiele" },
        { french: "un jeu vidéo/des jeux vidéo", german: "ein Videospiel/Videospiele" },
        { french: "la faim", german: "der Hunger" },
        { french: "avoir faim", german: "Hunger haben" },
        { french: "manger qc", german: "etw. essen" },
        { french: "souffler qc", german: "etw. ausblasen" },
        { french: "puis", german: "dann" },
        { french: "chanter", german: "singen" },
        { french: "un an", german: "ein Jahr" },
        { french: "avoir onze ans", german: "elf Jahre alt sein" },
        { french: "l’envie (f.)", german: "die Lust / das Verlangen" },
        { french: "avoir envie de faire qc", german: "Lust haben, etw. zu tun" },
        { french: "sur", german: "auf" },
        { french: "une surprise", german: "eine Überraschung" },
        { french: "avoir", german: "haben" },
        { french: "un mois", german: "ein Monat" },
        { french: "une année", german: "ein Jahr" },
        { french: "janvier (m.)", german: "Januar" },
        { french: "février (m.)", german: "Februar" },
        { french: "mars (m.)", german: "März" },
        { french: "avril (m.)", german: "April" },
        { french: "mai (m.)", german: "Mai" },
        { french: "juin (m.)", german: "Juni" },
        { french: "juillet (m.)", german: "Juli" },
        { french: "août (m.)", german: "August" },
        { french: "septembre (m.)", german: "September" },
        { french: "octobre (m.)", german: "Oktober" },
        { french: "novembre (m.)", german: "November" },
        { french: "décembre (m.)", german: "Dezember" },
        { french: "quand", german: "wann" },
        { french: "le premier", german: "der Erste" },
        { french: "l’âge (m.)", german: "das Alter" },
        { french: "Tu as quel âge?", german: "Wie alt bist du?" },
        { french: "il s’appelle", german: "er heißt" },
        { french: "la Pentecôte", german: "Pfingsten" },
        { french: "Noël (m.)", german: "Weihnachten" },
        { french: "le nouvel an", german: "das Neujahr" },
        { french: "le baptême", german: "die Taufe" },
        { french: "le 14 Juillet", german: "der 14. Juli (frz. Nationalfeiertag)" },
        { french: "Pâques", german: "Ostern" },
        { french: "le mariage", german: "die Hochzeit" }
    ],
    unit4: [
        { french: "un collège", german: "eine weiterführende Schule (Collège)" },
        { french: "une cour", german: "ein Hof" },
        { french: "un élève/une élève", german: "ein Schüler/eine Schülerin" },
        { french: "un cours", german: "eine Unterrichtsstunde" },
        { french: "l’allemand (m.)", german: "Deutsch (Schulfach)" },
        { french: "un retard", german: "eine Verspätung" },
        { french: "être en retard", german: "zu spät sein" },
        { french: "un CDI", german: "eine Mediothek / eine Schulbibliothek" },
        { french: "une cantine", german: "eine Kantine" },
        { french: "une infirmerie", german: "eine Krankenstation" },
        { french: "Aïe!", german: "Aua!" },
        { french: "un pied", german: "ein Fuß" },
        { french: "jouer", german: "spielen" },
        { french: "Balzac, Honoré de", german: "Honoré de Balzac (frz. Schriftsteller)" },
        { french: "une journée", german: "ein Tag (Verlauf)" },
        { french: "une heure", german: "eine Stunde" },
        { french: "sept heures", german: "sieben Uhr" },
        { french: "sept heures et demie", german: "halb acht" },
        { french: "sept heures moins le quart", german: "Viertel vor sieben" },
        { french: "sept heures et quart", german: "Viertel nach sieben" },
        { french: "un lit", german: "ein Bett" },
        { french: "demi/demie", german: "halb" },
        { french: "les toilettes (f.pl.)", german: "die Toiletten" },
        { french: "un quart", german: "ein Viertel" },
        { french: "huit heures et quart", german: "Viertel nach acht" },
        { french: "midi", german: "Mittag" },
        { french: "après", german: "nach" },
        { french: "rentrer", german: "nach Hause gehen" },
        { french: "à la maison", german: "zu Hause" },
        { french: "six heures moins le quart", german: "Viertel vor sechs" },
        { french: "chez qn", german: "bei jdm." },
        { french: "la télévision", german: "der Fernseher" },
        { french: "commencer", german: "anfangen" },
        { french: "Quelle heure est-il?", german: "Wie spät ist es?" },
        { french: "à quelle heure?", german: "um wie viel Uhr?" },
        { french: "de … à", german: "von … bis" },
        { french: "une clé", german: "ein Schlüssel" },
        { french: "une clé USB", german: "ein USB-Stick" },
        { french: "lundi (m.)", german: "Montag" },
        { french: "aller", german: "gehen / fahren" },
        { french: "ne … pas", german: "nicht" },
        { french: "la 6eA", german: "die 6A (Schulklasse)" },
        { french: "une minute", german: "eine Minute" },
        { french: "une classe", german: "eine Klasse" },
        { french: "sous", german: "unter" },
        { french: "une salle de cours", german: "ein Klassenraum" },
        { french: "Excusez-moi.", german: "Entschuldigen Sie." },
        { french: "Excuse-moi.", german: "Entschuldige." },
        { french: "une place", german: "ein Platz" },
        { french: "la main", german: "die Hand" },
        { french: "la récréation", german: "die Pause" },
        { french: "retrouver qn/qc", german: "jdn./etw. wiederfinden / treffen" },
        { french: "en 6eB", german: "in der 6B (Schulklasse)" },
        { french: "raconter qc", german: "etw. erzählen" },
        { french: "Il/Elle est à qui?", german: "Wem gehört das?" },
        { french: "Je ne sais pas.", german: "Ich weiß nicht." },
        { french: "Ce ne sont pas mes affaires.", german: "Das sind nicht meine Sachen." },
        { french: "discuter (de qc)", german: "(über etw.) diskutieren" },
        { french: "un professeur/une professeure", german: "ein Lehrer/eine Lehrerin" },
        { french: "le temps", german: "die Zeit / das Wetter" },
        { french: "l’emploi (m.) du temps", german: "der Stundenplan" },
        { french: "mardi (m.)", german: "Dienstag" },
        { french: "mercredi (m.)", german: "Mittwoch" },
        { french: "jeudi (m.)", german: "Donnerstag" },
        { french: "vendredi (m.)", german: "Freitag" },
        { french: "samedi (m.)", german: "Samstag" },
        { french: "dimanche (m.)", german: "Sonntag" },
        { french: "un mot", german: "ein Wort" },
        { french: "un gymnase", german: "eine Turnhalle" },
        { french: "un rêve", german: "ein Traum" },
        { french: "cool (fam.)", german: "cool (ugs.)" },
        { french: "cliquer", german: "klicken" },
        { french: "notre/nos", german: "unser/unsere" },
        { french: "votre/vos", german: "euer/eure; Ihr/Ihre" },
        { french: "leur/leurs", german: "ihr/ihre" },
        { french: "une interrogation", german: "eine Klassenarbeit" },
        { french: "quelque chose", german: "etwas" },
        { french: "un sac", german: "eine Tasche" },
        { french: "faire qc", german: "etw. machen" },
        { french: "une copie", german: "eine Kopie" },
        { french: "un exercice", german: "eine Übung" },
        { french: "si", german: "ob / wenn" },
        { french: "comme ça", german: "so / auf diese Weise" },
        { french: "comme", german: "wie / als" },
        { french: "les devoirs (m. pl.)", german: "die Hausaufgaben" },
        { french: "avoir raison", german: "Recht haben" },
        { french: "une partie", german: "ein Teil" },
        { french: "la fin", german: "das Ende" },
        { french: "un titre", german: "ein Titel" },
        { french: "derrière", german: "hinter" },
        { french: "l’E.P.S. (f.)", german: "Sportunterricht" },
        { french: "les arts plastiques (m.)", german: "Kunstunterricht" },
        { french: "les S.V.T. (f.)", german: "Biologie/Geowissenschaften" },
        { french: "la technologie", german: "Technik" },
        { french: "l’anglais (m.)", german: "Englisch" },
        { french: "les mathématiques (f.)", german: "Mathematik" },
        { french: "l’histoire-géo (f.)", german: "Geschichte/Erdkunde" },
        { french: "l’éducation musicale (f.)", german: "Musikunterricht" },
        { french: "le français", german: "Französisch (Schulfach)" }
    ],
    unit5: [
        { french: "un quartier", german: "ein Stadtviertel" },
        { french: "Batignolles", german: "Batignolles (Stadtteil in Paris)" },
        { french: "le, la dix-septième", german: "der/die siebzehnte" },
        { french: "un arrondissement", german: "ein Arrondissement (Stadtbezirk)" },
        { french: "une photo", german: "ein Foto" },
        { french: "un parc", german: "ein Park" },
        { french: "le roller", german: "Inlineskaten" },
        { french: "une avenue", german: "eine Allee" },
        { french: "Interclub 17", german: "Interclub 17 (Name eines Clubs)" },
        { french: "une activité", german: "eine Aktivität" },
        { french: "tout le monde", german: "alle / jeder" },
        { french: "un stand", german: "ein Stand" },
        { french: "une crêpe", german: "ein Crêpe" },
        { french: "un taxi", german: "ein Taxi" },
        { french: "passer", german: "vorbeigehen / verbringen" },
        { french: "la nuit", german: "die Nacht" },
        { french: "une entrée", german: "ein Eingang" },
        { french: "le soir", german: "der Abend" },
        { french: "ce soir", german: "heute Abend" },
        { french: "un jour", german: "ein Tag" },
        { french: "A plus! (fam.)", german: "Bis später! (ugs.)" },
        { french: "ma puce (fam.)", german: "mein Schatz (ugs.)" },
        { french: "A plus, ma puce!", german: "Bis später, mein Schatz!" },
        { french: "une voiture", german: "ein Auto" },
        { french: "en voiture", german: "mit dem Auto" },
        { french: "loin", german: "weit (weg)" },
        { french: "à pied", german: "zu Fuß" },
        { french: "aller faire qc", german: "etw. tun gehen" },
        { french: "un appartement", german: "eine Wohnung" },
        { french: "une pièce", german: "ein Zimmer" },
        { french: "une salle de bains", german: "ein Badezimmer" },
        { french: "un salon", german: "ein Wohnzimmer" },
        { french: "une chambre d’enfant", german: "ein Kinderzimmer" },
        { french: "une salle à manger", german: "ein Esszimmer" },
        { french: "les W.-C.", german: "die Toilette" },
        { french: "un couloir", german: "ein Flur" },
        { french: "une table", german: "ein Tisch" },
        { french: "à table", german: "zu Tisch! / Essen ist fertig!" },
        { french: "un repas", german: "eine Mahlzeit" },
        { french: "minuit (m.)", german: "Mitternacht" },
        { french: "le matin", german: "der Morgen" },
        { french: "un tour", german: "eine Runde / ein Spaziergang" },
        { french: "le samedi", german: "der Samstag" },
        { french: "l’après-midi (m./f.)", german: "der/die Nachmittag" },
        { french: "faire du judo", german: "Judo machen" },
        { french: "l’athlétisme (m.)", german: "Leichtathletik" },
        { french: "je voudrais …", german: "ich möchte …" },
        { french: "le bruit", german: "der Lärm" },
        { french: "tard", german: "spät" },
        { french: "une cuisine", german: "eine Küche" },
        { french: "quitter qc", german: "etw. verlassen" },
        { french: "des spaghettis (m. pl.)", german: "Spaghetti" },
        { french: "déjà", german: "schon / bereits" },
        { french: "le basket(ball)", german: "Basketball" },
        { french: "le volley(ball)", german: "Volleyball" },
        { french: "le hand-ball", german: "Handball" },
        { french: "l’équitation (f.)", german: "Reiten" },
        { french: "le cyclisme", german: "Radsport" },
        { french: "le ski", german: "Skifahren" },
        { french: "la natation", german: "Schwimmen" },
        { french: "la danse", german: "Tanzen" },
        { french: "le théâtre", german: "Theater" },
        { french: "une guitare", german: "eine Gitarre" },
        { french: "le tennis", german: "Tennis" },
        { french: "comme", german: "wie / als" },
        { french: "à droite", german: "rechts" },
        { french: "à gauche", german: "links" },
        { french: "une boulangerie", german: "eine Bäckerei" },
        { french: "tout droit", german: "geradeaus" },
        { french: "un café", german: "ein Café" },
        { french: "traverser qc", german: "etw. überqueren" },
        { french: "un carrefour", german: "eine Kreuzung" },
        { french: "tourner", german: "abbiegen / drehen" },
        { french: "pour faire qc", german: "um etw. zu tun" },
        { french: "beaucoup", german: "viel" },
        { french: "Merci beaucoup!", german: "Vielen Dank!" },
        { french: "la poste", german: "die Post" },
        { french: "une piscine", german: "ein Schwimmbad" },
        { french: "Vous pouvez répéter, s’il vous plaît?", german: "Können Sie das bitte wiederholen?" },
        { french: "un champion/une championne", german: "ein Champion/eine Meisterin" },
        { french: "un numéro", german: "eine Nummer" },
        { french: "un combat", german: "ein Kampf" },
        { french: "vraiment", german: "wirklich" },
        { french: "même", german: "sogar / selbst / gleich" },
        { french: "une interview", german: "ein Interview" },
        { french: "est-ce que", german: "(Fragewort, keine Übersetzung)" },
        { french: "gagner qc", german: "etw. gewinnen" },
        { french: "poser qc", german: "etw. stellen / legen" },
        { french: "une question", german: "eine Frage" },
        { french: "Comment est-ce que ...?", german: "Wie ...?" },
        { french: "tomber", german: "fallen" },
        { french: "faire mal", german: "weh tun" },
        { french: "pourquoi?", german: "warum?" },
        { french: "parce que", german: "weil" },
        { french: "trop", german: "zu / zu viel" },
        { french: "nul", german: "blöd / doof / schlecht" },
        { french: "C’est trop nul! (fam.)", german: "Das ist total blöd! (ugs.)" },
        { french: "avoir mal", german: "Schmerzen haben" },
        { french: "le parc des Batignolles", german: "der Batignolles-Park" },
        { french: "un portable", german: "ein Handy" },
        { french: "un SMS", german: "eine SMS" },
        { french: "un film", german: "ein Film" },
        { french: "la soif", german: "der Durst" },
        { french: "avoir soif", german: "Durst haben" },
        { french: "prendre qc", german: "etw. nehmen" },
        { french: "une gaufre", german: "eine Waffel" },
        { french: "coûter", german: "kosten" },
        { french: "Ça coûte combien?", german: "Wie viel kostet das?" },
        { french: "combien (de)", german: "wie viel(e)" },
        { french: "un euro/des euros", german: "ein Euro/Euro" },
        { french: "un centime", german: "ein Cent" },
        { french: "un vendeur/une vendeuse", german: "ein Verkäufer/eine Verkäuferin" },
        { french: "un coca", german: "eine Cola" },
        { french: "une eau minérale", german: "ein Mineralwasser" },
        { french: "un jus de pomme", german: "ein Apfelsaft" },
        { french: "l’eau (f.)", german: "das Wasser" },
        { french: "une pomme", german: "ein Apfel" },
        { french: "un jus", german: "ein Saft" },
        { french: "une orange", german: "eine Orange" },
        { french: "un diabolo menthe", german: "Limonade mit Minzsirup" },
        { french: "Ça fait combien?", german: "Wie viel macht das?" },
        { french: "un client/une cliente", german: "ein Kunde/eine Kundin" },
        { french: "Bonne journée!", german: "Schönen Tag!" },
        { french: "la planche à voile", german: "das Windsurfen" },
        { french: "le ski nautique", german: "Wasserski" },
        { french: "une maison des jeunes", german: "ein Jugendhaus" },
        { french: "un terrain de foot", german: "ein Fußballplatz" },
        { french: "un club de foot", german: "ein Fußballverein" },
        { french: "un club sportif", german: "ein Sportverein" },
        { french: "une école de musique", german: "eine Musikschule" },
        { french: "un glacier", german: "eine Eisdiele" },
        { french: "un coiffeur/une coiffeuse", german: "ein Friseur/eine Friseurin" },
        { french: "une papeterie", german: "ein Schreibwarengeschäft" },
        { french: "un supermarché", german: "ein Supermarkt" },
        { french: "un grand magasin", german: "ein Kaufhaus" },
        { french: "un kiosque", german: "ein Kiosk" },
        { french: "une bibliothèque", german: "eine Bibliothek" }
    ],
    unit6: [
        { french: "une fête", german: "ein Fest / eine Feier" },
        { french: "une fête", german: "ein Fest / eine Feier" },
        { french: "une fête nationale", german: "ein Nationalfeiertag" },
        { french: "les gens(m. pl.)", german: "die Leute" },
        { french: "un bal", german: "ein Ball / Tanzfest" },
        { french: "un bal", german: "ein Ball / Tanzfest" },
        { french: "grand/grande", german: "groß" },
        { french: "un feu/des feux", german: "ein Feuer / Feuer (Pl.)" },
        { french: "un feu d’artifice", german: "ein Feuerwerk" },
        { french: "une tour", german: "ein Turm" },
        { french: "la tour Eiffel", german: "der Eiffelturm" },
        { french: "danser", german: "tanzen" },
        { french: "le TGV", german: "der TGV (frz. Hochgeschwindigkeitszug)" },
        { french: "une personne", german: "eine Person" },
        { french: "l’arrivée )f.)", german: "die Ankunft" },
        { french: "un problème", german: "ein Problem" },
        { french: "téléphoner à qn", german: "jdn. anrufen / mit jdm. telefonieren" },
        { french: "téléphoner à qn", german: "jdn. anrufen / mit jdm. telefonieren" },
        { french: "rester", german: "bleiben" },
        { french: "hier", german: "gestern" },
        { french: "un journal/des journaux", german: "eine Zeitung / Zeitungen" },
        { french: "un journal/des journaux", german: "eine Zeitung / Zeitungen" },
        { french: "les vacances (f. pl.)", german: "die Ferien / der Urlaub" },
        { french: "les vacances (f. pl.)", german: "die Ferien / der Urlaub" },
        { french: "dernier/dernière", german: "letzter/letzte" },
        { french: "triste/triste", german: "traurig" },
        { french: "intéressant/intéressante", german: "interessant" },
        { french: "très", german: "sehr" },
        { french: "bon/bonne", german: "gut" },
        { french: "peut-être", german: "vielleicht" },
        { french: "une gare", german: "ein Bahnhof" },
        { french: "Lyon", german: "Lyon (Stadt in Frankreich)" },
        { french: "un chanteur/une chanteuse", german: "ein Sänger / eine Sängerin" },
        { french: "oublier qc", german: "etw. vergessen" },
        { french: "petit/petite", german: "klein" },
        { french: "enfin", german: "endlich / schließlich" },
        { french: "enfin", german: "endlich / schließlich" },
        { french: "un chapeau", german: "ein Hut" },
        { french: "joli/jolie", german: "hübsch / schön" },
        { french: "une robe", german: "ein Kleid" },
        { french: "long/longue", german: "lang" },
        { french: "un pantalon", german: "eine Hose" },
        { french: "vert/verte", german: "grün" },
        { french: "content/contente", german: "zufrieden / froh" },
        { french: "content/contente", german: "zufrieden / froh" },
        { french: "avant", german: "vor / bevor" },
        { french: "mettre qc", german: "etw. anziehen / etw. stellen / legen" },
        { french: "mettre qc", german: "etw. anziehen / etw. stellen / legen" },
        { french: "la Place de la Bastille", german: "der Place de la Bastille (Platz in Paris)" },
        { french: "mauvais/mauvaise", german: "schlecht" },
        { french: "donner qc à qn", german: "jdm. etw. geben" },
        { french: "Quoi?", german: "Was?" },
        { french: "une casquette", german: "eine Kappe / Schirmmütze" },
        { french: "une casquette", german: "eine Kappe / Schirmmütze" },
        { french: "la poche", german: "die Tasche (z.B. Hosentasche)" },
        { french: "la poche", german: "die Tasche (z.B. Hosentasche)" },
        { french: "demander (qc) à qn", german: "jdn. (etw.) fragen / jdn. um etw. bitten" },
        { french: "demander (qc) à qn", german: "jdn. (etw.) fragen / jdn. um etw. bitten" },
        { french: "entre", german: "zwischen / herein" },
        { french: "montrer qc à qn", german: "jdm. etw. zeigen" },
        { french: "parler à qn", german: "mit jdm. sprechen" },
        { french: "autre/autre", german: "anderer/andere" },
        { french: "rencontrer qn", german: "jdn. treffen / begegnen" },
        { french: "rencontrer qn", german: "jdn. treffen / begegnen" },
        { french: "aider qn", german: "jdm. helfen" },
        { french: "un courriel", german: "eine E-Mail" },
        { french: "une couleur", german: "eine Farbe" },
        { french: "bleu/bleue", german: "blau" },
        { french: "blanc/blanche", german: "weiß" },
        { french: "rouge/rouge", german: "rot" },
        { french: "jaune/jaune", german: "gelb" },
        { french: "surtout", german: "vor allem / besonders" },
        { french: "un vêtement", german: "ein Kleidungsstück" },
        { french: "noir/noire", german: "schwarz" },
        { french: "gris/grise", german: "grau" },
        { french: "un jean", german: "eine Jeans" },
        { french: "une basket", german: "ein Turnschuh / Sneaker" },
        { french: "une jupe", german: "ein Rock" },
        { french: "un anorak", german: "ein Anorak / eine Windjacke" },
        { french: "une chemise", german: "ein Hemd" },
        { french: "une veste", german: "eine Jacke / ein Sakko" },
        { french: "une chaussure", german: "ein Schuh" },
        { french: "un pull", german: "ein Pullover" },
        { french: "les fringues f. (fam.)", german: "Klamotten (ugs.)" },
        { french: "un short", german: "eine kurze Hose / Shorts" },
        { french: "un sweat", german: "ein Sweatshirt" },
        { french: "un blouson", german: "eine Jacke / Blouson" },
        { french: "un blouson", german: "eine Jacke / Blouson" },
        { french: "un poème", german: "ein Gedicht" },
        { french: "un sketch", german: "ein Sketch / eine Sketcheinlage" },
        { french: "un sandwich", german: "ein Sandwich / belegtes Brot" },
        { french: "une boisson", german: "ein Getränk" },
        { french: "une tarte flambée", german: "ein Flammkuchen" },
        { french: "une pizza", german: "eine Pizza" },
        { french: "des chips (f.)", german: "Chips" }
    ],
    unit7: [
        { french: "une semaine", german: "eine Woche" },
        { french: "un reportage", german: "eine Reportage / ein Bericht" },
        { french: "une ville", german: "eine Stadt" },
        { french: "un assistant/une assistante", german: "ein Assistent / eine Assistentin" },
        { french: "un endroit", german: "ein Ort / eine Stelle" },
        { french: "un touriste/une touriste", german: "ein Tourist / eine Touristin" },
        { french: "le Louvre", german: "der Louvre (Museum in Paris)" },
        { french: "un musée", german: "ein Museum" },
        { french: "une cathédrale", german: "eine Kathedrale / ein Dom" },
        { french: "Notre-Dame", german: "Notre-Dame (Kathedrale in Paris)" },
        { french: "la Défense", german: "La Défense (Stadtviertel in Paris)" },
        { french: "moderne", german: "modern" },
        { french: "l’Arc de triomphe (m.)", german: "der Triumphbogen (in Paris)" },
        { french: "visiter qc", german: "etw. besichtigen / besuchen" },
        { french: "beau", german: "schön" },
        { french: "Il fait beau.", german: "Es ist schönes Wetter." },
        { french: "faire de l’escalade", german: "klettern / Bergsteigen" },
        { french: "chaud/chaude", german: "heiß / warm" },
        { french: "chaud/chaude", german: "heiß / warm" },
        { french: "Il fait chaud.", german: "Es ist heiß." },
        { french: "la vue", german: "die Aussicht / der Blick" },
        { french: "un restaurant", german: "ein Restaurant" },
        { french: "une boutique", german: "ein Geschäft / eine Boutique" },
        { french: "une boutique", german: "ein Geschäft / eine Boutique" },
        { french: "un souvenir", german: "ein Andenken / eine Erinnerung" },
        { french: "un souvenir", german: "ein Andenken / eine Erinnerung" },
        { french: "un bureau", german: "ein Büro / ein Schreibtisch" },
        { french: "un bureau", german: "ein Büro / ein Schreibtisch" },
        { french: "un bureau", german: "ein Büro / ein Schreibtisch" },
        { french: "Eiffel, Gustave", german: "Gustave Eiffel (frz. Ingenieur)" },
        { french: "écrire qc à qn", german: "jdm. etw. schreiben" },
        { french: "une carte", german: "eine Karte" },
        { french: "une carte postale", german: "eine Postkarte" },
        { french: "une carte postale", german: "eine Postkarte" },
        { french: "le vent", german: "der Wind" },
        { french: "Il y a du vent.", german: "Es ist windig." },
        { french: "beaucoup de", german: "viel / viele" },
        { french: "le temps", german: "das Wetter / die Zeit" },
        { french: "Quel temps fait-il?", german: "Wie ist das Wetter?" },
        { french: "froid/froide", german: "kalt" },
        { french: "neiger", german: "schneien" },
        { french: "Il fait mauvais.", german: "Es ist schlechtes Wetter." },
        { french: "pleuvoir", german: "regnen" },
        { french: "Il pleut.", german: "Es regnet." },
        { french: "Il fait froid.", german: "Es ist kalt." },
        { french: "lire qc/qc à qn", german: "etw. lesen / jdm. etw. vorlesen" },
        { french: "lire qc/qc à qn", german: "etw. lesen / jdm. etw. vorlesen" },
        { french: "Cher …/Chère …", german: "Lieber … / Liebe …" },
        { french: "papi/papy (fam.)", german: "Opa (ugs.)" },
        { french: "mamie ugs.", german: "Oma (ugs.)" },
        { french: "génial/géniale", german: "genial / großartig" },
        { french: "génial/géniale", german: "genial / großartig" },
        { french: "la Joconde", german: "die Mona Lisa" },
        { french: "une bise (fam.)", german: "ein Küsschen (ugs.)" },
        { french: "une bise (fam.)", german: "ein Küsschen (ugs.)" },
        { french: "Coucou!", german: "Hallo! (ugs.)" },
        { french: "Comment allez-vous?", german: "Wie geht es Ihnen?" },
        { french: "un million", german: "eine Million" },
        { french: "un kilomètre", german: "ein Kilometer" },
        { french: "tôt (adv.)", german: "früh" },
        { french: "un bus", german: "ein Bus" },
        { french: "une station", german: "eine Station / Haltestelle" },
        { french: "une station", german: "eine Station / Haltestelle" },
        { french: "le métro", german: "die U-Bahn / Metro" },
        { french: "le métro", german: "die U-Bahn / Metro" },
        { french: "fatigué/fatiguée", german: "müde / erschöpft" },
        { french: "par jour", german: "pro Tag / täglich" },
        { french: "par jour", german: "pro Tag / täglich" },
        { french: "un moyen de transport", german: "ein Verkehrsmittel / Transportmittel" },
        { french: "un peu", german: "ein wenig / etwas" },
        { french: "la gare de l’Est", german: "der Ostbahnhof (in Paris)" },
        { french: "un ticket", german: "eine Fahrkarte / ein Ticket" },
        { french: "un ticket", german: "eine Fahrkarte / ein Ticket" },
        { french: "écologique/écologique", german: "ökologisch / umweltfreundlich" },
        { french: "écologique/écologique", german: "ökologisch / umweltfreundlich" },
        { french: "en train", german: "mit dem Zug" },
        { french: "un avion", german: "ein Flugzeug" },
        { french: "un marché", german: "ein Markt" },
        { french: "un marché aux puces", german: "ein Flohmarkt" },
        { french: "ne … pas de", german: "kein / keine" },
        { french: "pas de problème", german: "kein Problem" },
        { french: "une chose", german: "eine Sache / ein Ding" },
        { french: "une chose", german: "eine Sache / ein Ding" },
        { french: "un exemple", german: "ein Beispiel" },
        { french: "par exemple", german: "zum Beispiel" },
        { french: "on peut", german: "man kann" },
        { french: "pratique/pratique", german: "praktisch" },
        { french: "ne … plus", german: "nicht mehr" },
        { french: "ne … plus de", german: "kein(e) mehr" },
        { french: "plus de problème", german: "kein Problem mehr" },
        { french: "inventer qc", german: "etw. erfinden" },
        { french: "cher/chère", german: "teuer / lieb" },
        { french: "ouvert/ouverte", german: "offen / geöffnet" },
        { french: "adorer qn/qc", german: "jdn./etw. sehr mögen / lieben" },
        { french: "désirer qc", german: "etw. wünschen / begehren" },
        { french: "(je suis) désolé/désolée", german: "(es tut mir) leid" },
        { french: "peu de", german: "wenig / wenige" },
        { french: "beaucoup de", german: "viel / viele" },
        { french: "un grand huit", german: "Achterbahn" },
        { french: "vrai/vraie", german: "wahr / echt" }
    ]
};

// Function to get vocabulary for a specific unit (remains the same)
function getVocabularyForUnit(unitId) {
    return vocabulary[unitId] || [];
}
