// js/vocabulary.js

const vocabulary = {
    unit1: [
        { french: "Bienvenue!", german: "Willkommen!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Salut! (fam.)", german: "Hallo! / Servus! / Tschüss!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Sarah", german: "Sarah", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "et", german: "und", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "toi", german: "du / dir (z.B. und du? -> et toi?)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "moi", german: "ich / mir (z.B. ich auch -> moi aussi)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "je m’appelle", german: "ich heiße", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Ça va?", german: "Wie geht's?", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "oui", german: "ja", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "merci", german: "danke", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "A plus! (fam.)", german: "Bis später!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Bonjour!", german: "Guten Tag! / Hallo!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Au revoir!", german: "Auf Wiedersehen!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un ami/une amie", german: "ein Freund/eine Freundin", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Bonjour, les amis!", german: "Hallo, Freunde!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "bien (adv.)", german: "gut (Adverb)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "une chanson", german: "ein Lied", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Venez!", german: "Kommt!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "à", german: "in / zu / an (Präposition)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un copain/une copine (fam.)", german: "ein Kumpel/eine Freundin", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "à demain", german: "bis morgen", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "voilà", german: "da ist/sind / hier ist/sind / sieh da!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "une bise (fam.)", german: "ein Küsschen (auf die Wange)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "pour", german: "für", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Quoi?", german: "Was?", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Je pique une crise! (fam.)", german: "Ich krieg 'ne Krise! / Ich raste aus!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "vite (adv.)", german: "schnell (Adverb)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Appelle la police!", german: "Ruf die Polizei!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "pas de dessert", german: "kein Nachtisch / kein Dessert", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "dans le désert", german: "in der Wüste", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "aussi", german: "auch", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un bonbon", german: "ein Bonbon", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "C’est bon!", german: "Das ist gut! / Lecker!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un croissant", german: "ein Croissant", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un ballon", german: "ein Ball / ein Ballon", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un lapin", german: "ein Kaninchen", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un volcan", german: "ein Vulkan", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "la main", german: "die Hand", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un chien", german: "ein Hund", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un crayon", german: "ein Bleistift", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un éléphant", german: "ein Elefant", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un enfant", german: "ein Kind", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "une maison", german: "ein Haus", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un gratin", german: "ein Gratin / ein Auflauf", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "mon petit chat", german: "mein Kätzchen / mein kleiner Schatz (Kosename)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un", german: "eins (Zahl) / ein (Artikel)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "deux", german: "zwei", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "trois", german: "drei", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "quatre", german: "vier", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "cinq", german: "fünf", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "six", german: "sechs", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "sept", german: "sieben", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "huit", german: "acht", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "neuf", german: "neun", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "dix", german: "zehn", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "onze", german: "elf", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "douze", german: "zwölf", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un CDI", german: "eine Mediothek / eine Schulbibliothek", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un café", german: "ein Café / ein Kaffee", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "une pharmacie", german: "eine Apotheke", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un bureau de poste", german: "ein Postamt / eine Post", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un restaurant", german: "ein Restaurant", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un parc", german: "ein Park", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "une boulangerie", german: "eine Bäckerei", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un cinéma", german: "ein Kino", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "une médiathèque", german: "eine Mediathek", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "dans la rue", german: "auf der Straße", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Paris", german: "Paris", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Viens!", german: "Komm!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "papa", german: "Papa", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Miaou!", german: "Miau!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Ouah, ouah!", german: "Wau, wau!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "S.P.A.", german: "Tierschutzverein", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "qui (Fragepronomen)", german: "wer (Fragepronomen)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Qui est-ce?", german: "Wer ist das?", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Attention!", german: "Achtung! / Vorsicht!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "non", german: "nein", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Pardon.", german: "Entschuldigung. / Verzeihung.", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Comment?", german: "Wie? / Wie bitte?", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "ce/c’", german: "das / es", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "c’est", german: "das ist / es ist", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "je suis", german: "ich bin", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Tu t’appelles comment?", german: "Wie heißt du?", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "bizarre", german: "komisch / seltsam", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un chat", german: "eine Katze", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "mais", german: "aber", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "ici", german: "hier", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "tu es", german: "du bist", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "de/d’", german: "von / aus (Präposition)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "super (inv.)", german: "super / toll (unveränderlich)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un garçon", german: "ein Junge", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "une fille", german: "ein Mädchen", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "il est", german: "er ist", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "elle est", german: "sie ist", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "fantastique", german: "fantastisch", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "une dame", german: "eine Dame / eine Frau", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un monsieur", german: "ein Herr", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Toulouse", german: "Toulouse", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Strasbourg", german: "Straßburg", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Nice", german: "Nizza", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Brest", german: "Brest", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "madame …", german: "Frau …", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Bof!", german: "Na ja! / Geht so.", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "(fam.)", german: "(ugs. - umgangssprachlich)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "Bof! (fam.)", german: "Na ja! (ugs.) / Geht so. (ugs.)", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un cochon d’Inde", german: "ein Meerschweinchen", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un poisson", german: "ein Fisch", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un cheval/des chevaux", german: "ein Pferd/Pferde", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "une souris", german: "eine Maus", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un cochon", german: "ein Schwein", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un canari", german: "ein Kanarienvogel", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un perroquet", german: "ein Papagei", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un rat", german: "eine Ratte", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "une tortue", german: "eine Schildkröte", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "une perruche", german: "ein Wellensittich", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un serpent", german: "eine Schlange", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "un hamster", german: "ein Hamster", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" },
        { french: "A tout à l’heure!", german: "Bis später! / Bis gleich!", image: "images/vocab/placeholder.png", audio: "audio/vocab/placeholder.mp3" }
    ],
    unit2: [
        // Vocabulary for Unit 2 will go here
    ]
    // Add other units as needed
};

// Function to get vocabulary for a specific unit (remains the same)
function getVocabularyForUnit(unitId) {
    return vocabulary[unitId] || [];
}
